system:
  logo: 'picture/logo.png'
  secret: '3.1415926a?'
  file-path: home/picture/
spring:
  datasource:
    url: jdbc:mysql://82.156.108.104:3306/scmdev?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root123
  jpa:
    hibernate:
      ddl-auto: update